name: Deploy docs to dev

on:
  workflow_dispatch: {}

jobs:
  dev:
    uses: ./.github/workflows/deploy.yml
    permissions:
      id-token: write
    with:
      stage: dev
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}