name: Deploy to GitHub Pages

on:
  push:
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - uses: actions/upload-artifact@v7
        with:
          name: github-pages
          path: |
            README.md
            images/cover.png
            schema.json
            install.sh
            install.ps1
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.0